import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ConnectionContext from "./context/ConnectionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> 
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body className={"bg-white text-black" + inter}>
        <ConnectionContext>
          <Navbar />
          {children}
        </ConnectionContext>
      </body>
    </html>
  );
}
