import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import ConnectionContext from "../context/ConnectionContext";
import clsx from "clsx";
import Footer from "@/components/Footer";

const inter = Poppins({ weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body className={clsx(inter, "bg-[#eff0eb] flex flex-col")} >
        <ConnectionContext>
          <Navbar />
          <main className="container flex-1 flex-grow">
          {children}
          </main>
          <Footer />
        </ConnectionContext>
        {modal}
        <div id="modal-root" />
      </body>
    </html>
  );
}
